export const FORM_CONTROL_MAP = {
  text: '',
  inputNumber: '',
  select: '',
  time: '',
  date: '',
  dateTime: '',
  cascader: '',
  treeselect: '',
  switch: '',
  slider: '',
  radio: '',
  checkbox: '',
  upload: '',
}
